import { StyleSheet } from "react-native";

export const authStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F7FA",
  },
  navBar: {
    backgroundColor: "#0D1F23",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#132E35",
  },
  navTitle: {
    color: "#AFB3B7",
    fontSize: 18,
    fontWeight: "500",
  },
  backButton: {
    padding: 8,
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 24,
  },
  title: {
    fontSize: 28,
    fontWeight: "600",
    color: "#0D1F23",
    marginBottom: 32,
    textAlign: "center",
  },
  input: {
    height: 52,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    paddingHorizontal: 16,
    marginBottom: 16,
    fontSize: 16,
    color: "#132E35",
    borderWidth: 1,
    borderColor: "#E8ECEF",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  button: {
    backgroundColor: "#2D4A53",
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 24,
    shadowColor: "#2D4A53",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
    paddingHorizontal: 24,
    marginLeft: 12,
    minWidth: 100,
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  linkText: {
    color: "#2D4A53",
    fontSize: 14,
    fontWeight: "500",
    textAlign: "center",
    marginTop: 24,
    textDecorationLine: "underline",
  },
  linksContainer: {
    marginTop: 24,
    alignItems: "center",
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(13, 31, 35, 0.7)",
  },
  modalView: {
    width: "90%",
    backgroundColor: "#F5F7FA",
    borderRadius: 16,
    padding: 24,
    maxHeight: "60%", // Ajusta según necesidad
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
    borderWidth: 1,
    borderColor: "#E8ECEF",
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "600",
    marginBottom: 24,
    color: "#0D1F23",
    textAlign: "center",
  },
  scrollContainer: {
    paddingBottom: 16,
  },
  fixedFooter: {
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#E8ECEF",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  buttonSave: {
    backgroundColor: "#2D4A53",
  },
  buttonCancel: {
    backgroundColor: "#E8ECEF",
  },
  buttonSaveText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "600",
  },
  buttonCancelText: {
    color: "#5A636A",
    fontSize: 15,
    fontWeight: "600",
  },
});
